### ISSUE TITLE
Connecting to a profile is not working

### ISSUE THREAD

**Issue by am** [cghdev/alfred-pritunl#3]
After updating Pritunl Client to `v1.3.3457.61` I no longer can connect. The workflow is able to list the different profiles, but connecting is not working anymore.

**Comment by cghdev** [comment]
can you connect correctly by using the Pritunl GUI?

**Comment by am** [comment]
Hi @cghdev, yes, I can connect using the GUI. Is there any way to see logs from the alfred workflow that could be useful to debug?

**Comment by am** [comment]
This did the trick! This time I've used the installer from the [Pritunl Client](https://client.pritunl.com/) website, instead of using homebrew to install, since the latest version in homebrew is not the latest released. 
It's now working, so feel free to close the issue. I'm unsure if this is a issue with a specific version, or if it happens with Pritunl Client when installed using homebrew...

**Comment by cghdev** [comment]
Awesome! thanks for confirming
